### PR TITLE
fix: ensure node 4 compat

### LINKED ISSUE #66: start doesn't work on node v4.4.5
Just FYI, `const entry = ['.', '/'].includes(first)` throws an error on `includes` as it's an ES6 feature

### PR DESCRIPTION
**Pull request by marionebl**
*  add 'use strict' to all files for node 4 block-scoping
*  remove usage of `Array.prototype.includes` in resolveEntryFile
*  rename `resolveEntryFile` to `resolveEntry`
*  move multiple `resolveEntry` implementations to `lib/resolve-entry`
*  order imports in `bin/build` according to length
*  add lib to allowed files in manifest

fixes #66

### CODE REVIEW

File: bin/start.js [hunk 1]
```diff
@@ -1,8 +1,10 @@
+'use strict'
+
+const resolveEntry = require('../lib/resolve-entry')
```
Comment (marionebl) [inline bin/start.js]: @yoshuawuyts Are you okay with this? The current project setup seems to suggest you'd like to keep together in very flat organisation.

**Comment by marionebl** [comment]
Going forward with this to fix the issues with node version < 6. We can revisit any stylistic issues later.
